sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y firefox xvfb libav-tools"
  - "gem install bundler"
script: "bundle exec rspec"
