language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.2
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y firefox xvfb libav-tools"
  - "gem install bundler"
script: "rspec"
